### PR TITLE
Risk matrix custom cells

### PR DESCRIPTION
**Pull request by Rundez**
### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [X] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [X] Check the commit's or even all commits' message 
- [X] Check if your code additions will fail linting checks
- [X] Remember: Add issue description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the **ID of the Issue** associated with this PR
- [X] Documentation: Have a look at the [PP365 User manual](https://puzzlepart.github.io/prosjektportalen-manual/) and consider the need for updates to be made. Updates can be done directly into the 'Kladd' branch or by providing information to test team for implementation.

### Description

This change makes it possible to add custom cells to the risk matrix. Colors, headers, text and number of cells can be modified to the organizations needs. 
A json (txt) file is fetched from the PP hubsite, stored in siteassets (https://{tenant}.sharepoint.com/sites{hubsite}/SiteAssets). The config file have to be named custom-cells.txt and have a certain format. A sample file is provided in the Risk-matrix code. 

### How to test

1. Upload the custom-cells.txt into the PP-instance siteassets.
2. Change the cell-color or header names. (or add some cells)
3. Notice the changes
4. Remove the config file, and the matrix should be rendered as usual. 

### Update of documentation
- [X] Check if user manual requires update
  - [X] Yes
    - Update user manual

### Relevant issues (if applicable)

💔Thank you!

### CODE REVIEW

**Comment by tarjeieo** [comment]
Can we instead merge this?

**Comment by olemp** [comment]
> Can we instead merge this?

First I'd need to look through the code.

**Comment by Remi749** [comment]
FYI: Merged this with latest dev

**Comment by Remi749** [comment]
Rebased with latest 1.6.0 dev

**Comment by okms** [comment]
I suggest another rebase and and then merge this

**Pull request merged**
