### PR TITLE
Added description for site template

### PR DESCRIPTION
**Pull request by tarjeieo**
### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [X] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [X] Check the commit's or even all commits' message 
- [X] Check if your code additions will fail linting checks
- [X] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

Minor description added to site template

### How to test

Check if there is a site template description for the Prosjektområde site template under "Apply a template"

### Relevant issues (if applicable)

💔Thank you!

### CODE REVIEW

**Comment by pzljanb** [comment]
The template description is in place and looks good except for the norwegian letter æ, ø, å.
See picture for details.....

image

**Comment by olemp** [comment]
> The template description is in place and looks good except for the norwegian letter æ, ø, å.
> See picture for details.....
> 
> image

Guess we need to encode @tarjeieo

**Comment by tarjeieo** [comment]
Garrrr..... Guess so!

**Comment by tarjeieo** [comment]
Finally... Unfortunately, setting the picture is not available with the version of PnP PowerShell we are using today...

image

**Comment by okms** [comment]
Issue #417 will open up the possibility for setting the thumbnail

**Comment by danielwiese** [comment]
Tested, OK

**Pull request merged**
