### PR TITLE
Permission configuration list for projects

### LINKED ISSUE #387: Copy permissions from configuration list to projects
**Is your feature request related to a problem? Please describe.**
When creating new projects, you might want to copy permissions to the new projects. This is today done with the "Portfolio administrators" group. This is a working approach, but not a flexible one.

**Describe the solution you'd like**
I suggest using a portfolio list that holds the configuration for the permission configuration. The PP setup wizard iterates through this list and copies permissions to the project. This will only be applied to the SharePoint-site of the project, not the M365 group/Team.

Tasks to complete this

- A list "Permission Configuration" at the portfolio level with the following columns
    - SharePoint group name
    - Permission level (`Read`, `Edit`, `Full Control` - prob needs to be in norwegian though, `Les`, `Rediger`, `Full kontroll`). Description: Definerer rettighetsnivå på SharePoint-området til prosjektet.
- A default item in this list: **"Portfolio administrators"** with permission level `Full control` (replaces the setting from the wizard).
- Update wizard code. Use this list to set initial permissions. Remove the "give portfolio administrators access" switch

NB: It is possible for group owners to remove the permissions after the wizard has run. This is intended.

### PR DESCRIPTION
**Pull request by olemp**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check your code additions will fail linting checks
- [x] Remember: Add PR description to [Changelog](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description
Permission configuration list for projects.

### How to test
See #387

### Relevant issues (if applicable)
Closes #387

### CODE REVIEW

**Comment by pzljanb** [comment]
The "give portfolio administrators access" switch is succesfully remove from the project configurator.
As by this design all configuration done in "Permission configurator" list will be added to all new projects.
Is this as intended @tarjeieo ?

(Only way to remove default permissions as configured in list is to manually remove after project is created.)

**Comment by olemp** [comment]
> The "give portfolio administrators access" switch is succesfully remove from the project configurator.
> As by this design all configuration done in "Permission configurator" list will be added to all new projects.
> Is this as intended @tarjeieo ?
> 
> (Only way to remove default permissions as configured in list is to manually remove after project is created.)

See related issue #387 @pzljanb @danielwiese 

> NB: It is possible for group owners to remove the permissions after the wizard has run. This is intended.

**Comment by tarjeieo** [comment]
Yes, I would say this is as intended as per now. We could consider giving users some more information about this in the wizard or elsewhere, but after all, the permission settings are created by portfolio managers and then should probably be relevant for all projects.

Sidenote; Could probably me a correlation between "project template" and "permission setup" - but that's a discussion for later.

**Comment by pzljanb** [comment]
Solution is good :-)

**Pull request merged**
