### PR TITLE
Added "Last Report Date" to Portfolio Overview "Project Status" view

### LINKED ISSUE #393: Show "Last report date" on the status report page and as a column in portfolio view
**Is your feature request related to a problem? Please describe.**
When browsing projects and status report values in the portfolio overview/portfolio status, it would be nice to see when the last report was made.

**Describe the solution you'd like**
* Show a datefield on the project status page that will be included as part of the project status page snapshot.
* Show a datefield for when the last report was made in the portfolio overview (if you select this column).

**Additional context**
This is by default stored in the "modified" field - however, this field is also used by the project properties item as well. Not sure how we handle this in a good way. Input @olemp ?

### PR DESCRIPTION
**Pull request by Petterandre**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check if your code additions will fail linting checks
- [x] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

Adds:
GtLastReportDate column and adds to ProjectStatus CT.
Adds element to Prosjektkolonner list with ID 30
Adds ID 30 to default "Project Status" view
Adds "Created" date to title on Project status page. (Will be used later in Snapshots)
Updates the field when clicking on "Publish report" in project.

### How to test

1. Create a new project report.
2. Publish the report.
3. View SitePages/Porteføljeoversikt.aspx

### Relevant issues (if applicable)

Closes #393

Note:
Does not use "Modified" date from the list element, meaning it does not work retroactively for already published documents as per suggestion in the issue. 
💔Thank you!

### CODE REVIEW

**Comment by olemp** [comment]
@Petterandre can you resolve conflicts

**Comment by Petterandre** [comment]
> @Petterandre can you resolve conflicts

@olemp Done and Done.

**Comment by pzljanb** [comment]
Error when no previous reports. Has to be handled.

**Comment by pzljanb** [comment]
Handled nicely in new PR 👍

**Pull request merged**
