### PR TITLE
Enhancement/support portfolio insights for ad groups

### PR DESCRIPTION
**Pull request by ThomasGranheim**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check your code additions will fail linting checks
- [x] Remember: Add PR description to [Changelog](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

AD groups added to SP group will now also get portfolio insight.
Fix to bug: https://github.com/Puzzlepart/prosjektportalen365/issues/332

### How to test

- [ ] 1. Add AD group to portfolio insight SP group
- [ ] 2. Make sure users in AD group get portfolio insight
- [ ] 3. Also, test that users added directly to SP group get portfolio insight

💔Thank you!

### CODE REVIEW

**Comment by olemp** [comment]
@ThomasGranheim Is https://github.com/Puzzlepart/prosjektportalen365/pull/339 related to this? Does it need a separate PR, or can it just be added to this? Also, can you resolve the conflicts <3

**Review by olemp — CHANGES_REQUESTED** [review]
Fix conflicts (update from dev), and update CHANGELOG (same change as in separate PR)

**Comment by ThomasGranheim** [comment]
Does it look OK now? Fetched from the dev branch and merged it into new feature branch. Also added the CHANGELOG commit to this PR.

**Review by olemp — APPROVED** [review]
🚀

**Pull request merged**
