### PR TITLE
Updated changelog

### PR DESCRIPTION
**Pull request by Petterandre**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check your code additions will fail linting checks
- [x] Remember: After PR is closed, add PR description to [Changelog](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md)

### Description

Updated changelog. Uncertain about the layout, but noticeable changes for users should be listed.

### How to test

N/A

### Relevant issues (if applicable)
N/A
💔Thank you!

### CODE REVIEW

**Comment by Remi749** [comment]
image

Bytt "Improvements" med "Changed" for å følge regelsettet for Changelogs.

**Review by Remi749 — CHANGES_REQUESTED** [review]
Bytt "Improvements" med "Changed" for å følge regelsettet for Changelogs.

**Comment by Petterandre** [comment]
Done.

**Review by olemp — APPROVED** [review]
Good stuff

**Pull request merged**
