### PR TITLE
#192

### PR DESCRIPTION
**Pull request by olemp**
In the template `ProjectContentTypeId` need to be added with the id of the new content type in the list `Prosjekter`:

```json
{
    "Version": "1.1.4",
    "Parameters": {
        "ProvisionSiteFields": "Kolonner for Prosjektportalen (Prosjekt)",
        "ProjectContentTypeId": "0x0100805E9E4FEAAB4F0EABAB2600D30DB70C"
    }
}
```

The task `SetupProjectInformation ` uses this ID with fallback to the base content type (0x0100805E9E4FEAAB4F0EABAB2600D30DB70C).

Final step is to provide this content type ID in ProjectInformation when synchronizing properties.

### CODE REVIEW

**Comment by olemp** [comment]
This pull request is still a work in progress @tarjeieo 😁

**Comment by olemp** [comment]
I see some issues with supporting different types of project propertes in the same installation. According to https://github.com/Puzzlepart/prosjektportalen-bygganlegg/ there is some extra status fields, and these needs to be added to the status report content type which is shared within the hub site (portfolio). 

This PR has support for doing this for project properties, but it makes it much more complex to also support this for project status.

What big wins do we get from supporting this in the same site collection? For PP 2 the customers are using separate site collections?

cc @okms @tarjeieo

**Comment by olemp** [comment]
(Mentioned you @okms in case you have some valuable input)

**Comment by okms** [comment]
Extend the sync method to add fields that do not currently exists on the status sync list. dont't extend the core content type for that list beyond what is in the pp base install.

**Comment by olemp** [comment]
But if we want to support several types of project in the same portfolio.. 

e.g.

1. Bygg
2. Anlegg
3. Standard

We don't want `Bygg` to see properties for `Standard` and `Anlegg`, and we don't want `Standard` to see properties for `Bygg `and `Anlegg` etc etc.

This is already solved for project properties by inheriting the PP `Prosjekt` content type when installing the `Bygg og anlegg` extension (https://github.com/Puzzlepart/prosjektportalen365-bygg).

**Comment by okms** [comment]
And this cannot be solved by having multiple content types in the status report list? I assume we're not trying to support one project beeing both of type a and b, i.e. there will just one type of project per group/site collection? the exception being the hub site which has to keep tabs on all types of projects

**Comment by olemp** [comment]
Yes, it can be solved by using mulitple content types, but it adds some level of complexity, so we should think of the gains before we go for this approach. It requires some changes to this repository.

What's left for this PR is to add support for multiple content types in ProjectStatus (`SharePointFramework\ProjectWebParts\src\components\ProjectStatus\index.tsx` ).

This could be done by adding a `ContentTypeId` property when creating the status report item in the function `_redirectNewStatusReport`, but we have to know the content type ID for the project status content type instance. This could be done by retrieiving the value of `SourceContentTypeId` from the project property item (see commit https://github.com/Puzzlepart/prosjektportalen365/pull/195/commits/66535950476ce2c3c5f3ba4a56ac727443fa5842).

**Comment by olemp** [comment]
Oh no. `SourceContentTypeId ` on the project properties item is the content type id of the project property item in the portfolio, not the project status content type id.

**Comment by olemp** [comment]
So say we have a new project type with a custom template for `Anlegg`.

It has a content type `Prosjekt - Anlegg` with content type id `0x0100805E9E4FEAAB4F0EABAB2600D30DB70C01` which inherits from `Prosjekt` (0x0100805E9E4FEAAB4F0EABAB2600D30DB70C).

It also has a content type `Prosjektstatus - Anlegg` with content type id `0x010022252E35737A413FB56A1BA53862F6D501` which inherits from `Prosjektstatus` (0x010022252E35737A413FB56A1BA53862F6D5).

These IDs need to be provided in the template parameters (example: https://github.com/Puzzlepart/prosjektportalen365-bygg/blob/master/Templates/Portfolio/Prosjektmaler/Bygg%20og%20anlegg.txt).

Then in the provisioning these need to be stored on the project property item so they can be accessed from the SPFx components. 

That's my proposed solution.

Any input on this @okms @tarjeieo?

**Comment by tarjeieo** [comment]
Great thinking, sounds very elegant (and I'm curious on how this juggling of content types will work in practice). Is it necessary to only specify the fields on the hub site? And then the reference to the project CT and status CT is sufficient to get the configuration in the project site?

A consequence: In the project portfolio, we would need to have additional fields only relevant for some of the content types, and then they would be blank for others. Alternatively we/users can create portfolio views per projectype/projectCT. A natural and acceptable consequence right?

**Comment by olemp** [comment]
Yes! That should be enough! The sync function is now adding all fields from the specified content type. Also added a field `TemplateParameters` which will contain a string representation of the template parameters. This can then be used throughout the SPFx solutions by retrieving the project property item (parse it and get the JSON again).

We could create separate views for different project types. The main views should only have fields that are common for all.

**Comment by olemp** [comment]
Another issue is the different phases for the different project types. We can easily change the term set id for all the taxonomy fields on the site itself, but the root list `Prosjekter` can only point to one term set.

Currently we're syncing the term set values from the project sites to the hub site list, and that won't work with several different term sets for the different project types.

Me and @tarjeieo had a quick chat and are thinking along the lines of introducing new text fields for the term set fields in the hub site list, and don't sync the taxonomy values itself.

Any input @okms? This PR would be mute without supporting this.

**Pull request merged**
