### PR TITLE
Added rich text and lineshift support

### PR DESCRIPTION
**Pull request by Rundez**
### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [X] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [X] Check the commit's or even all commits' message 
- [X] Check if your code additions will fail linting checks
- [x] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

Arbeidstilsynet asked for lineshift and rich text support in the Project information web part. Some fields could be hard to read when filled with a lot of text without the ability to format. 

### How to test

Edit project properties, write lineshift in a multi-line field. Lineshift will be rendered in the web part. 

💔Thank you!

### CODE REVIEW

**Review by olemp — CHANGES_REQUESTED** [review]
@Rundez Can you add an entry to the changelog?

**Comment by Rundez** [comment]
Added.

**Comment by pzljanb** [comment]
Tested OK,
Found that also coding like inline html tags can be used.
Is there a listing of which tags that can be used @Rundez ?

**Comment by Rundez** [comment]
I believe that most, if not all HTML tags can be used. 
@pzljanb

**Pull request merged**
