### PR TITLE
Changed Source-parameter in editFormUrl

### PR DESCRIPTION
**Pull request by siifux**
### Description

I have changed the Url that is set as a `&Source` parameter to not include the query param, so that you won't be redirected back to the spesific status report you came from. I have read the examples written in the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Location) for Location, and I think this solution will grab the Url without the query/hash.

### CODE REVIEW

**Review by tarjeieo — APPROVED** [review]
Strålende

**Review by olemp — APPROVED** [review]
Looks good @siifux 🔪

**Comment by pzljanb** [comment]
@siifux  This is not working. It continues to catch to report you are "coming from" before you created a new report.
Can be tested here: [CI Clean install environment](https://puzzlepart.sharepoint.com/sites/TestJan_v130_2/SitePages/Prosjektstatus.aspx#selectedReport=2)

Please add a "How to test" section fr the next test :-)

**Comment by siifux** [comment]
@pzljanb I see.. The editForm url still contains the `&Source` param set to the selected report you came from.. @olemp I still haven't gotten to test this case easily while coding since the change is in the @shared project, so should find a way to do that?

**Comment by siifux** [comment]
This is now tested, and works as expected with the npm packages updated 👏

**Pull request merged**
