### PR TITLE
Show status report summary on the front page #368

### PR DESCRIPTION
**Pull request by olemp**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check if your code additions will fail linting checks
- [x] Remember: Add issue description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the **ID of the issue** associated with this PR
- [x] Documentation: Have a look at the [PP365 User manual](https://puzzlepart.github.io/prosjektportalen-manual/) and consider the need for updates to be made. Updates can be done directly into the 'Kladd' branch or by providing information to test team for implementation.

### Description

Show status report summary on the front page. It can be toggled on and off in the web part properties and required data will only be fetched if it's set to visible.

image

It's set to be hidden by default.

image

If _Avkort kommentarer_ is set it will truncate the comments to the specified length and show the full status element in a tooltip.

image

### Relevant issues (if applicable)

#368

### CODE REVIEW

**Comment by Remi749** [comment]
@olemp, Would like to see a screenshot when there are visual changes, when possible could you add to the PR?

**Comment by olemp** [comment]
> @olemp, Would like to see a screenshot when there are visual changes, when possible could you add to the PR?

This is stil in progress :) My bad.

**Comment by Remi749** [comment]
Looks good, though it will take up a lot of space, how about only showing icons instead and have the tooltip like you've shown in the screenshot?

**Comment by Remi749** [comment]
Like this: 
image

**Comment by olemp** [comment]
> Like this: 
> 
> image
> 
> 

I will add a setting for only showing icon in another PR.

**Pull request merged**
