### PR TITLE
Upgrade Install script to use latest version of PnP.PowerShell

### PR DESCRIPTION
**Pull request by olemp**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check if your code additions will fail linting checks
- [x] Remember: Add issue description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the **ID of the issue** associated with this PR
- [x] Documentation: Have a look at the [PP365 User manual](https://puzzlepart.github.io/prosjektportalen-manual/) and consider the need for updates to be made. Updates can be done directly into the 'Kladd' branch or by providing information to test team for implementation.

### Description

Upgrade Install script to use latest version of `PnP.PowerShell`.

### Relevant issues (if applicable)
#417

### CODE REVIEW

**Comment by okms** [comment]
please see #421 for context on previous attempts

**Comment by damsleth** [comment]
I don't think setting `UpdateChildren` on `<FieldRefs>` will do anything, since it's `true` by default 😕
 
https://github.com/pnp/powershell/blob/499772c325510619684dd0ca0e933aa0b61e4e1c/src/Commands/ContentTypes/AddFieldToContentType.cs#L26

**Comment by olemp** [comment]
> I don't think setting `UpdateChildren` on `<FieldRefs>` will do anything, since it's `true` by default 😕
> 
> https://github.com/pnp/powershell/blob/499772c325510619684dd0ca0e933aa0b61e4e1c/src/Commands/ContentTypes/AddFieldToContentType.cs#L26

It fails at a later stage now though...

image

**Comment by olemp** [comment]
> > I don't think setting `UpdateChildren` on `<FieldRefs>` will do anything, since it's `true` by default 😕
> > https://github.com/pnp/powershell/blob/499772c325510619684dd0ca0e933aa0b61e4e1c/src/Commands/ContentTypes/AddFieldToContentType.cs#L26
> 
> It fails at a later stage now though...
> 
> image

Where `UpdateChildren` were not set..

**Comment by olemp** [comment]
> > > I don't think setting `UpdateChildren` on `<FieldRefs>` will do anything, since it's `true` by default 😕
> > > https://github.com/pnp/powershell/blob/499772c325510619684dd0ca0e933aa0b61e4e1c/src/Commands/ContentTypes/AddFieldToContentType.cs#L26
> > 
> > 
> > It fails at a later stage now though...
> > image
> 
> Where `UpdateChildren` were not set..

Actually it can't be `TRUE` by default as it works when setting it to true for all field refs.

**Comment by olemp** [comment]
@okms @Remi749 Please review 😻

**Review by Remi749 — APPROVED** [review]

**Pull request merged**
