### PR TITLE
Setting default site design for hub on install

### PR DESCRIPTION
**Pull request by okms**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check if your code additions will fail linting checks
- [x] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description
resolving issue #491 where we have to set a default site design when installing

### How to test
Run installer against a dev/test tenant which is in targeted release, i.e. has the new site template experience where you cannot select site design upon group creation

- [ ] Run installer
- [ ] Create a new project

The 'prosjektområde' template shoud automatically be applied.

### Relevant issues (if applicable)
#491

### CODE REVIEW

**Comment by olemp** [comment]
@okms Do we need to support skipping this step in the installer?

**Review by olemp — CHANGES_REQUESTED** [review]
@okms Do we need to support skipping this step in the installer?

**Review by olemp — APPROVED** [review]

**Comment by tarjeieo** [comment]
Shouldn't we merge into dev for PRs?

**Comment by olemp** [comment]
> Shouldn't we merge into dev for PRs?

Please change to `dev` @okms. We don't merge directly to **main**.

**Comment by okms** [comment]
@olemp @tarjeieo done

**Pull request merged**
