### PR TITLE
567 simple

### PR DESCRIPTION
**Pull request by tarjeieo**
### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [X] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [X] Check the commit's or even all commits' message 
- [X] Check if your code additions will fail linting checks
- [X] Remember: Add issue description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the **ID of the Issue** associated with this PR
- [X] Documentation: Have a look at the [PP365 User manual](https://puzzlepart.github.io/prosjektportalen-manual/) and consider the need for updates to be made. Updates can be done directly into the 'Kladd' branch or by providing information to test team for implementation.

### Description

Skipping applying navigation if it's an upgrade

### How to test

Please describe how someone else (a regular user without coding skills) can test this PR. In the form of a numbered list and checkboxes for Jan when the testing period occurs.

Example:

- 1. Upgrade a pre 1.2.7 install
- 2. Upgrade a post 1.2.7 install
- 3. Observe that the portfolio navigation is equal in the two cases

### Update of documentation
- [X] Check if user manual requires update

### Relevant issues (if applicable)

#567 

💔Thank you!

### CODE REVIEW

**Comment by tarjeieo** [comment]
Going back and forth here... With this change, we are not adding new navigation nodes to the top navigation bar on upgrade, nor are we resetting the navigation. 

It's of course possible to write an upgrade script that adds "missing" items to the navigation, but what if the customer doesn't want this functionality? Then it's always added back in case of an upgrade - which is not what we want either.

I'm leaving this PR more or less as-is, only adding an output to the install script that the project timeline page needs to be added to the navigation manually.

**Comment by tarjeieo** [comment]
Changed my mind - again! I'm adding the navigation node IF and only if the already installed version is pre-1.2.7. This should handle this in the better way IMO.

**Comment by okms** [comment]
We need to remember to backport this to #421

**Review by okms — APPROVED** [review]
Looks good. Note that SupportedUILanguages appears to do nothing when using PnP.PowerShell, so for Schema 2020/2 and newer this has no effect from my limited testing.

**Pull request merged**
