### PR TITLE
Show project tooltip when project is not accessible

### PR DESCRIPTION
**Pull request by tarjeieo**
### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [X] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [X] Check the commit's or even all commits' message 
- [X] Check if your code additions will fail linting checks
- [X] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

For project you cannot access because of 1. search delay, 2. no access, 3. no project properties or 4. hub change, I've added the project information tooltip plus an icon and a tooltip giving a notification message saying why you cannot access the project.

image

### How to test

Please describe how someone else can test this PR. In the form of a numbered list and checkboxes for Jan when the testing period occurs.

Example:

- [x] 1. Navigate to the project portfolio
- [x] 2. Observe that projects that are inaccessible now have an icon with a tooltip message
- [x] 3. Observe that you still get the project information tooltip
- [x] 4. Observe that the information in the project information tooltip matches the values of the project properties for the specific project

### Relevant issues (if applicable)

#563 #553 

💔Thank you!

### CODE REVIEW

**Comment by olemp** [comment]
> @tarjeieo Does it make sense to have a message saying _"Kan ikke hente data fra prosjektområdet"_ and also show the dialog with the project data? I think this can be confusing for the users.

Thoughts @okms? I think two hover effects in the same area will be confusing for the users. Especially with the misleading message.

**Comment by olemp** [comment]
> > > @tarjeieo Does it make sense to have a message saying _"Kan ikke hente data fra prosjektområdet"_ and also show the dialog with the project data? I think this can be confusing for the users.
> > 
> > 
> > Thoughts @okms? I think two hover effects in the same area will be confusing for the users. Especially with the misleading message.
> 
> I agree, I'll do some slight updates to the text and move it inside the existing dialog.

Ok, I created a separate component for the TitleColumn in [this commit](https://github.com/Puzzlepart/prosjektportalen365/pull/578/commits/c1f711ab3905ea4fadbbb188881f912f15f5955e). Makes it a bit more manageable.

**Comment by tarjeieo** [comment]
Actually, hold on 2 secs with merge

**Comment by tarjeieo** [comment]
> > Actually, hold on 2 secs with merge
> 
> Waited 2 seconds and now merging.

Thanks 4 waiting - go ahead

**Pull request merged**
