### PR TITLE
Fix for bug #353

### LINKED ISSUE #353: Cannot exit portfolio filter mode
**Describe the bug**
When using the portfolio filter functionality, there is no way to exit the dialog in 1.2.4

**To Reproduce**

1. Go to Portoflio overview
2. Click on Filter button
3. Try to exit

**Expected behavior**
Close the dialog

**Screenshots**
image

**About your setup**

- Browser [e.g. chrome, safari]: Edge chromium
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.2.4

**Additional context**

I think it would be nice to have both a close-button, plus allow clicking outside the dialog to close it.

### PR DESCRIPTION
**Pull request by olemp**
### Your checklist for this pull request
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check your code additions will fail linting checks
- [x] Remember: Add PR description to [Changelog](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description
Fix for #353.

### How to test
See #353

### Relevant issues (if applicable)
Closes #353

### CODE REVIEW

**Comment by pzljanb** [comment]
We have to use the 'How to test' section for each issue.
I have added a section in this issue on a "best guess" basis.

**Comment by olemp** [comment]
> We have to use the 'How to test' section for each issue.
> I have added a section in this issue on a "best guess" basis.

This is a PR, not an issue

**Comment by pzljanb** [comment]
> > We have to use the 'How to test' section for each issue.
> > I have added a section in this issue on a "best guess" basis.
> 
> This is a PR, not an issue

Sorry, my mistake.
We have to use the 'How to test' section for each PR

**Comment by olemp** [comment]
> > > We have to use the 'How to test' section for each issue.
> > > I have added a section in this issue on a "best guess" basis.
> > 
> > 
> > This is a PR, not an issue
> 
> Sorry, my mistake.
> We have to use the 'How to test' section for each PR

Alright. I though the section was to be used in the related issue.

**Comment by pzljanb** [comment]
> > > > We have to use the 'How to test' section for each issue.
> > > > I have added a section in this issue on a "best guess" basis.
> > > 
> > > 
> > > This is a PR, not an issue
> > 
> > 
> > Sorry, my mistake.
> > We have to use the 'How to test' section for each PR
> 
> Alright. I though the section was to be used in the related issue.

We will go thru the process of producing a new release in a meeting in the future.

But for now, this is the short background for the test section:
1. A problem or wish is described by using issues
2. The PR is representing the "solution" (how we have choosen to implement some new/ improved features)
3. The 'How to test' section in the PR is used to describe test steps for what we have implemented
    We should test what we have implemented, not what have been wished
    In this PR we should list the different "exit possibilities" that have be implemented
     (E.g. "Exit button" and/ or "Clicking outside the pane")

**Pull request merged**
