### PR TITLE
Fix for excel export 

### LINKED ISSUE #470: Excel export not working
**Describe the bug**
The new Excel expor as implemented in #469 does not work

**To Reproduce**
Tested on both:
https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Erfaringslogg.aspx
https://puzzlepart.sharepoint.com/sites/pp365_806139261/SitePages/Erfaringslogg.aspx

In both instances the Excel export button does not execute any actions
Receive the following error message:
_portfolio-aggregation-web-part_fe48ec74aed4be60f1441be7f5ec174e.js:1 Uncaught (in promise) Error: TypeError: Cannot set property 'define' of undefined_

**About your setup**
- Tested in Chrome and Edge

### PR DESCRIPTION
**Pull request by Petterandre**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check if your code additions will fail linting checks
- [x] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

Fixes Excel export for Portfolio overview and aggregated portfolios. Completely removes dynamic loading of dependencies as this appears to have been the main culprit for it failing.

PS: Changelog not updated due to it fixing already existing bug,

### How to test

- [ ] 1. Go to Portfolio Overview
- [ ] 2. Export to Excel
- [ ] 3. Repeat step 2 at all Aggregated portfolios

### Relevant issues (if applicable)

Closes #470

💔Thank you!

### CODE REVIEW

**Comment by olemp** [comment]
@Petterandre Did you continue on an old branch?

image

**Comment by Petterandre** [comment]
> @Petterandre Did you continue on an old branch?
> 
> image

@olemp Yes, stupidly. I did, however, merge dev into the branch, so it should be up to date

**Comment by pzljanb** [comment]
Tested OK in all portfolio views

**Comment by olemp** [comment]
> Tested OK in all portfolio views

The comment should be on the issue #460

**Pull request merged**
