### PR TITLE
Skipping overwrite of default content

### PR DESCRIPTION
**Pull request by tarjeieo**
### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [X] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [X] Check the commit's or even all commits' message 
- [X] Check if your code additions will fail linting checks
- [X] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

Skipping overwrite of default content to better support customizations.

### How to test

Please describe how someone else can test this PR. In the form of a numbered list and checkboxes for Jan when the testing period occurs.

Example:

- [ ] 1. Do modifications of portfolio views, columns, column configuration and insights graphs
- [ ] 2. Update PP to new version
- [ ] 3. Verfiy that customizations are not lost

### Relevant issues (if applicable)

💔Thank you!

### CODE REVIEW

**Comment by olemp** [comment]
What if we need to change the default config?

**Comment by tarjeieo** [comment]
> What if we need to change the default config?

We can always add new items. Don't see a scenario where we need to change existing - and in my opinion it's more important to "honor" customer customizations.

**Review by olemp — APPROVED** [review]

**Comment by pzljanb** [comment]
Removed 'Målsetting' from 'Avslutede prosjeter'
Added group by 'Tjenesteområde' on 'Alle prosjekter'
Removed 'Export to Excel' button on 'Erfaringslogg'
Enabled 'Show as etikett' on 'Konsekvens' column in 'Risikooversikt'

**Comment by pzljanb** [comment]
Etter update fungerte de fleste lokale tilpasninger ba, med unntak av :
[ ] Added group by 'Tjenesteområde' on 'Alle prosjekter'
Denne må testes en gang til...

**Comment by pzljanb** [comment]
> Etter update fungerte de fleste lokale tilpasninger som tiltenkt, med unntak av :
> [ ] Added group by 'Tjenesteområde' on 'Alle prosjekter'
> Denne må testes en gang til...

Da er den siste også testet med vellykket resultat :-)

**Pull request merged**
