### PR TITLE
Fixed Last Report Date loading when no report exists

### PR DESCRIPTION
**Pull request by Petterandre**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check if your code additions will fail linting checks
- [x] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

Fixes previous 393 merge when there is no report

### How to test

- [ ] 1. Go to project with 0 reports
- [ ] 2. Click Project status

### Relevant issues (if applicable)

#393 
💔Thank you!

### CODE REVIEW

**Review by olemp — CHANGES_REQUESTED** [review]
Can you resolve conflicts and add a more descriptive PR title (as it will be used for the commit message)?

image

image

**Comment by Petterandre** [comment]
> Can you resolve conflicts and add a more descriptive PR title (as it will be used for the commit message)?
> 
> image
> 
> image

Sorry about that, was supposed to be a draft, but was a little bit too quick on the trigger.

**Comment by Petterandre** [comment]
Added StartDateLabel by request from @Remi749

**Comment by Petterandre** [comment]
Rebased into newest dev. Should be fine now.

**Comment by olemp** [comment]
@Petterandre Is XLSX now included through package.json? The point with the dynamic loading was to avoid increasing the bundle size. The XLSX package is quite large.

FileSaver is still loaded dynamically?

image

**Comment by Petterandre** [comment]
> @Petterandre Is XLSX now included through package.json? The point with the dynamic loading was to avoid increasing the bundle size. The XLSX package is quite large.
> 
> FileSaver is still loaded dynamically?
> 
> image

No idea why has become a changed file in this PR, this was done in PR #469 and shouldn't be considered a changed file as that PR is merged. Rebased into dev after PR #469, may be the cause.

Was done to fix the export issue #460 . Again, dev branch should be up to date with that change. I wanted to maintain the dynamic loading for Filesaver to avoid having to include both in package.json

**Comment by pzljanb** [comment]
Tested OK

**Pull request merged**
