### PR TITLE
Feature/project timeline webpart

### PR DESCRIPTION
**Pull request by Remi749**
### Your checklist for this pull request

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [X] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [X] Check the commit's or even all commits' message 
- [X] Check if your code additions will fail linting checks
- [X] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

This pull request is for adding the new Projecttimeline portoflio webpart. More information here: #429 

### How to test

Please describe how someone else can test this PR. In the form of a numbered list and checkboxes for Jan when the testing period occurs.

Example:

- [ ] 1. Install PP365
- [ ] 2. Add projects with startDate and EndDate
- [ ] 3. Check out 'Prosjekttidslinje' webpart

### Relevant issues (if applicable)
#429

### CODE REVIEW

**Comment by olemp** [comment]
Will check it out @Remi749. 🚀

**Review by olemp — CHANGES_REQUESTED** [review]
Loving it! 

Can we do something with long project names though? Either let them wrap or increase width of the column.

image

**Comment by Remi749** [comment]
> Loving it!
> 
> Can we do something with long project names though? Either let them wrap or increase width of the column.
> 
> image

Thanks <3 Great feedback, I see you increased the width, would that suffice or should I wrap if it's above the current width?

**Comment by olemp** [comment]
> > Loving it!
> > Can we do something with long project names though? Either let them wrap or increase width of the column.
> > image
> 
> Thanks <3 Great feedback, I see you increased the width, would that suffice or should I wrap if it's above the current width?

Let's test it a bit after dev `CI` upgraded https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Home.aspx. We can create new issues if we decide to do more adjustments.

**Comment by pzljanb** [comment]
The column 'Prosjekttilknytning' in 'Tidslinjeinnhold' refer to the item in thu hubsite list 'Prosjekter',
this should be changed to the current projects list 'Prosjektegenskaper'.
Issue #457

**Pull request merged**
